# Generated by Django 2.1.7 on 2019-04-10 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_inicial', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Km Inicial')),
                ('km_final', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Km Final')),
                ('data_fechamento', models.DateField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('valor_por_litro', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor por Litro')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor Total')),
                ('nivel_rotacao', models.IntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta')], verbose_name='Nível de Rotação')),
                ('tipo_combustivel', models.IntegerField(choices=[(1, 'Gasolina'), (2, 'Álcool')], verbose_name='Tipo do Combustível')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Marca')),
                ('tipo_veiculo', models.IntegerField(choices=[(1, 'Carro Passeio'), (2, 'Motocicleta'), (3, 'Van'), (4, 'Ônibus')], verbose_name='Tipo do Veículo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Modelo')),
                ('cilindrada', models.IntegerField(verbose_name='Total de Cilindros')),
                ('ano', models.IntegerField(verbose_name='Ano do Modelo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tankyou.Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=6, verbose_name='Número da Placa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tankyou.Modelo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lancamento',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tankyou.Veiculo'),
        ),
    ]
